ALTER TABLE "TeacherProfile"
  ADD COLUMN "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "deleted_at" TIMESTAMPTZ;
ALTER TABLE "TeacherProfile" ALTER COLUMN "updated_at" DROP DEFAULT;

ALTER TABLE "ClassTeacherAssignment"
  ADD COLUMN "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "deleted_at" TIMESTAMPTZ;
ALTER TABLE "ClassTeacherAssignment" ALTER COLUMN "updated_at" DROP DEFAULT;

ALTER TABLE "ClassSubstitution"
  ADD COLUMN "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "deleted_at" TIMESTAMPTZ;
ALTER TABLE "ClassSubstitution" ALTER COLUMN "updated_at" DROP DEFAULT;
