export const REQUIRED_RUNTIME_ENVIRONMENT = [
  "APP_URL",
  "BETTER_AUTH_SECRET",
  "DATABASE_URL",
  "EMAIL_FROM",
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
];

export const OPTIONAL_RUNTIME_ENVIRONMENT = [
  "BETTER_AUTH_URL",
  "GCS_ARTIFACTS_BUCKET",
  "GCS_PROJECT_ID",
  "GOOGLE_APPLICATION_CREDENTIALS",
  "STORAGE_EMULATOR_HOST",
  "HATCHET_CLIENT_HOST_PORT",
  "HATCHET_CLIENT_TLS_STRATEGY",
  "HATCHET_CLIENT_TOKEN",
  "NODE_ENV",
  "PORTAL_BASE_URL",
  "PORTAL_MASTER_PASSWORD",
  "PORTAL_MASTER_USERNAME",
  "RESEND_API_KEY",
  "SMTP_HOST",
  "SMTP_PORT",
  "TRPC_DEV_DELAY_MS",
];
